### ISSUE TITLE
Just use prometheus container directly?

### ISSUE THREAD

**Issue by eero-t** [mbenabda/promtool-container-image#1]
Why not just use prometheus image directly:
```
docker run --entrypoint /bin/promtool -it --rm --user nobody --network none --cap-drop ALL <registry>/prom/prometheus:<version> <options>
```
?

**Comment by mbenabda** [comment]
Hi @eero-t 

To save bandwidth and time in CI pipelines (shared CI runners are often billed per minute, so that saves money as well):
```sh
$ docker inspect prom/prometheus:v2.40.4 | jq -r '.[0].Size'
223443991
$ docker inspect mbenabda/promtool:v2.40.4 | jq -r '.[0].Size'
106133023
```

**Comment by eero-t** [comment]
Fair point.  Container managers cache the images, so it could be just a one-time bandwidth+time cost per node & prometheus version, but I guess such CI runners use from-scratch VMs where such state does not persist.

Any idea why upstream Prometheus project does not provide such a container (in DockerHub, for every release)?

**Comment by mbenabda** [comment]
> Any idea why upstream Prometheus project does not provide such a container (in DockerHub, for every release)?

To be honest i do not know. It may be worth suggesting it to the upstream project maintainers though !
